### PR TITLE
EZP-24744 - Increase password security

### PR DESCRIPTION
**Pull request by pkamps**
Upstream pull request:
https://github.com/ezsystems/ezpublish-legacy/pull/1322

### CODE REVIEW

**Comment by peterkeung** [comment]
This won't produce a noticeable change for upgraded sites, since the setting in site.ini won't get overridden for existing sites. (This is good.) But in the case where someone decides to use this for an existing site, they'll need to alter the database schema. Shouldn't we add a note to site.ini alerting developers to this fact?

**Comment by benkmugo** [comment]
+1 for adding a note to the ini

**Comment by peterkeung** [comment]
Not sure what I was thinking when I said the setting in site.ini won't get overridden. It *will* get overridden when upgrading. This will break existing sites, and thus there needs to be an update script / SQL file.

**Comment by pkamps** [comment]
The password hash type is stored in the ezuser DB table. So it won't break authentication for an old installation if you change to a new password hash algorithm.
The authentication is not taking the settings for the hash algorithm but uses the DB hash type info to chose the hash algorithm.
For new user accounts, it will generate the password hash using the settings configuration.

There is a setting to update the password hashes automatically once a user logs in (not enabled by default).

**Comment by peterkeung** [comment]
What I'm referring to specifically is that the password_hash database field needs to be updated to be VARCHAR(255) instead of VARCHAR(50).

**Comment by pkamps** [comment]
That is indeed an issue: It will generate password hashes longer than 50 chars and won't be able to fully store it. Then the user won't be able to authenticate anymore.

**Comment by pkamps** [comment]
I'm ok adding a note to the ini file. But it raises a bigger issue: releases.

It's a bit confusing to me how eZ organizes the releases. There is the release management on github:
https://github.com/ezsystems/ezpublish-legacy/releases

And there are directories in the source code for DB updates:
https://github.com/ezsystems/ezpublish-legacy/tree/master/update/database/mysql

I do not know how to connect a release like "2017.10.0" with and upgrade directory called "6.12".

In terms of upgrade documentation to a specific release I cannot find anything that would describe the upgrade path to a community release like "2017.8.1"

Before this pull request, it was always easy to upgrade to the latest lovestack master. You simply take all recent files from master and just overwrite the files in the installation you want to upgrade.

It would be great if we could avoid releases all together because it would add additional work to manage our lovestack fork. It would be nice to have any version of the lovestack and always be able to upgrade to the latest master version.

With changes to DB schema (and potentially scripts in the future), the upgrade process is getting more complex.
In the past when there were "real" ezp releases:, you need to know the current ezp version and then execute DB schema updates in update/database/mysql/x.x.x to reach the next release version.

I'm considering to change the DB schema update process. What about having a single script to update the DB and rely on a DB schema version?
So the script would use a schema version number stored in the DB:

UPDATE ezsite_data SET value='123' WHERE name='db-schema-version';

All updates we develop to the schema would require a specific schema version and in case it successfully executes the DB schema changes, it then increases the DB schema version.
A developer could just run the script and the script is smart enough to ignore old schema updates (current schema version is greater) and only execute new schema updates (current schema version is smaller). Then there is no need to stick to the idea of releases -- at least for the DB schema.

**Comment by peterkeung** [comment]
I'm +1 to that approach for DB schema changes. Not that WordPress is the gold standard, but I can say from experience that WordPress and its plugins follow that approach and it works great. Where it breaks down is if you need to intersperse simple DB schema changes with longer running update scripts.

**Comment by pkamps** [comment]
I created a new pull request to leave a note in the site.ini file. The pull request also has a PHP script to manage DB schema changes using a DB schema version number like I described in my previous comment:
https://github.com/mugoweb/ezpublish-legacy/pull/75

**Pull request merged**
