### PR TITLE
Patch for SQL injection in legacy search

### PR DESCRIPTION
**Pull request by ernestob**
Original patch for default search vulnerability

### CODE REVIEW

**Comment by ernestob** [comment]
Hi @peterkeung @pkamps @thiagocamposviana @benkmugo @dougplant @moismailzai 

Can you review this patch for the Default search SQL injection

**Comment by peterkeung** [comment]
Seems to be a pattern with eZ to quote integers. I'd love to understand why.

I'm +1 to all of the escaping.

Is there a test we can run regarding the vulnerability?

**Comment by moismailzai** [comment]
+1 to all of the escaping as well.

What kind of performance related issues are you seeing @ernestob? If those eZDB::instance() are expensive / causing the issues, maybe you can borrow their escaping functions instead? Looks like they're just wrappers for pg_escape_string and mysqli_real_escape_string built-ins:

lib/ezdb/classes/ezpostgresqldb.php
``` php
function escapeString( $str )
{
    $str = str_replace("\0", '', $str);
    $str = pg_escape_string( $str );
    return $str;
}
```


lib/ezdb/classes/ezmysqlidb.php

``` php
function escapeString( $str )
{
    if ( $this->IsConnected )
    {
        return mysqli_real_escape_string( $this->DBConnection, $str );
    }
    else
    {
        eZDebug::writeDebug( 'escapeString called before connection is made', __METHOD__ );
        return mysql_escape_string( $str );
    }
}
```

**Comment by pkamps** [comment]
It's probably a bit cleaner **not** to quote the integer values (if the mysql field is of the type integer) - and it's a tiny bit faster:
http://stackoverflow.com/questions/6781976/mysql-quote-numbers-or-not

Looks like it's the same for PostgreSQL:
https://github.com/tgriesser/knex/issues/1001

Not sure about oracle.

**Comment by pkamps** [comment]
I can only imagine that quoting the integer values is a way to protect against SQL injections - but I cannot find any reference in the Internet. It does not seem to be common practise. In fact, I see people saying it's not helping at all.

I think the current code is doing unnecessary transformation:

`$value = (int)$db->escapeString( $searchParams['value'] );
`
Looking at the escapeString function, I don't see that being different to:

`$value = (int) $searchParams['value'];
`

Verdict: I think we could simplify that patch quite a bit

-1

**Comment by peterkeung** [comment]
Keeping in mind that this came from eZ, we should find a way to communicate any proposed changes to them. They don't seem to care to post these patches to the open source repo (https://github.com/ezsystems/ezpublish-legacy) so maybe we should be opening up a pull request there.

**Comment by dougplant** [comment]
first guess was using an empty string to represent 'zero'

but this comment seems more interesting:

http://stackoverflow.com/questions/6781976/mysql-quote-numbers-or-not

"
...

|mysql>SELECTCOUNT(1)FROMtest_no 
WHEREvarchar_num=0000194701461220130201115347;+----------+|COUNT(1)|+----------+|1|+----------+1rowinset,1warning 
(7.94sec)|

...
"

... not sure I totally understand it, though.

I tend to trust the existing code idiom. People like D. Rethans had a 
hand in it.

**Comment by benkmugo** [comment]
I'm in favour of using #27 instead of this PR

**Comment by pkamps** [comment]
Closed in favour of #27.

**Pull request closed without merging**
