### PR TITLE
Object info has a new section "Published version" containing all details if it exists

### PR DESCRIPTION
**Pull request by pkamps**
This pull requests affects the "object_information.tpl" template. It is shown if you edit a content object of if you look at the version history for a content object.

http://devmanage.lovestack.mugo.ca/content/history/58
http://devmanage.lovestack.mugo.ca/content/edit/58

The top section "Object information" contains the details:
**ID** (object ID)
**Created** (creation time + creator user name)
**Modified** (object modification + user name of that last modification)
**Published version** (version id number)

The **Modified** details are buggy currently - see:
https://github.com/ezsystems/ezpublish-legacy/pull/1296

The pull request 1296 fixes the issue - but I think it's worth considering to also re-organize the object information a little. This pull request fixes the buggy **Modified** details and additionally puts the details from **Modified** and **Published version** into a dedicated section called 'Published version'.

See the 2 screenshots:

NEW:
screen shot 2017-05-09 at 15 12 16

OLD:
screen shot 2017-05-09 at 15 12 08

### CODE REVIEW

**Comment by peterkeung** [comment]
I don't mind the reorganization, but did you purposely rename Modified to Created under "Published version"? Regardless of the other fix, it's technically inaccurate with that change of wording, because you are outputting the modified date.

That also brings up the question about whether an editor cares more about seeing the created or modified dates for the published version. They're usually quite close, and I don't have a strong opinion about changing it from modified to created.

**Comment by benkmugo** [comment]
I'd show both created and modified information for the published version. Plenty of space in the sidebar.

**Comment by pkamps** [comment]
I don't like the idea of listing the both the creation, modification date. It's a technical detail most editors are not interested in, I think. The version list has those 2 timestamps and it's probably to right view to show these details.

I think an editor just wants to know when the current public version was published - technically that's the modification timestamp of the published version. So I think I should call it 'Modified:'.

I do 2 more re-organisations:
1) Swap version owner name with timestamp to make it consistent for both groups
2) Swap the 'ID:' with the 'Created:' field

**Comment by pkamps** [comment]
New version I suggest:
screen shot 2017-05-15 at 09 43 06

**Comment by pkamps** [comment]
New version I suggest:
screen shot 2017-05-15 at 09 49 44

**Comment by peterkeung** [comment]
I am +1 with the wording change to "Published" while still using the "modified" property.

**Comment by benkmugo** [comment]
+1 on that

**Pull request merged**
