### PR TITLE
Sort by trashed field

### PR DESCRIPTION
**Pull request by pkamps**
Upstream pull request: https://github.com/ezsystems/ezpublish-legacy/pull/1439

### CODE REVIEW

**Comment by peterkeung** [comment]
The test is technically not correct because the field should be ezcontentobject_trash.trashed not ezcontentobject_tree.trashed

Should we send the second parameter to eZContentObjectTreeNode::createSortingSQLStrings() since that's how eZContentObjectTrashNode calls it? https://github.com/ezsystems/ezpublish-legacy/blob/2019.03/kernel/classes/ezcontentobjecttrashnode.php#L232

(I know this is getting a bit academic at that point, because all we're doing is testing that it returns the string "trashed" after the table name!)

**Comment by carlosmauri** [comment]
Right, good catch @peterkeung ,

The second parameter of the createSortingSQLStrings allows us to specify a different table name than the default **ezcontentobject_tree**

I would update the lines 68 & 69 of the ezcontentobjecttreenode_test2.php to be
```
...
$result = eZContentObjectTreeNode::createSortingSQLStrings( $sortList, 'ezcot');
$this->assertEquals( 'ezcontentobject_tree.trashed asc',
...
```
FROM ezcontentobject_trash ezcot
ezcot is a table alias of ezcontentobject_trash, from ezcontentobjecttrashnode.php (line 277)
but maybe for the unit test there's no need to send the table alias?

**Comment by pkamps** [comment]
I learned the unit tests are not supposed to only test real use cases. Instead you want to write as many tests to cover all possible use cases. That also includes use cases that will cause an error in that kernel function.
Concretely for this: the second parameter is optional, so it's a valid unit test I wrote but it would make sense to add a lot more tests (the one you suggested). Maybe with a sort parameter that does not exists, a function call with a 3rd parameter (I think there is one - did not check now). So we have to draw a line somewhere - at a minimum we want to make ez system happy so that they accept your pull request. My suggestion is to add a 2nd test like you suggested. Could be a good practise for Carlos.

**Comment by pkamps** [comment]
Upstream pull request: https://github.com/ezsystems/ezpublish-legacy/pull/1440

**Pull request merged**
