### PR TITLE
Enhanced patch from ezsystem for input escaping of custom tag attribu…

### PR DESCRIPTION
**Pull request by pkamps**
Enhanced (actually working) version of:
https://github.com/ezsystems/ezpublish-legacy/pull/1249

### CODE REVIEW

**Comment by pkamps** [comment]
there is seems to be another patch coming from ez - let's wait for that - please do not merge for now.

**Comment by pkamps** [comment]
OK, patch from ez system is exactly how we patched it. Ready to get merged.

**Comment by peterkeung** [comment]
+1

**Comment by benkmugo** [comment]
weird case, but valid
+1

**Pull request merged**
