### PR TITLE
Reworked .gitignore

### PR DESCRIPTION
**Pull request by pkamps**
Reworked .gitignore to ignore additional extensions and settings - var folder now empty with just a dedicated .gitignore file.

It would allow you to clone the project and add client specific extensions, settings and assets (in the var dir) without having those showing up as new files.

### CODE REVIEW

**Comment by benkmugo** [comment]
+1, merge away.

**Comment by ernestob** [comment]
I think it is a better approach to keep the ignoring rule for the var folder in the global `.gitignore` file. This way all the ignore rules are in one place.

This is the approach I have used to handle git disability to track empty directories.
I usually add a .gitkeep file
```
# Ignore everything from the /var directory
/var/*
.
.
.
# Add this to the end of the .gitignore file
# Except for any .gitkeep file in the tree. This is added only to keep directories in the repository.
!.gitkeep
```
Having this in place and whenever I need to track a directory, all I need to do is this `touch my_empty_dir/.gitkeep`, no need to add anything in the file.

**Comment by pkamps** [comment]
I agree it's cleaner to just have a single .gitignore file. Pull request adjusted.

**Comment by peterkeung** [comment]
As discussed just now, the addition of the extension and settings rules seems catered to committing back to this repo only. We need to consider how this will get used on actual client projects.

**Comment by pkamps** [comment]
I now changed it. The new version is a better fit for client projects: only ignoring everything in the var folder. To keep the var folder it now contains a '.gitkeep' file.
This pull request is also removing var/webdav/root/info.txt a superfluous  file.

**Comment by benkmugo** [comment]
@pkamps the .gitignore is missing the .gitkeep exclusion rule that Ernesto mentioned no?

**Comment by pkamps** [comment]
You're right - I updated .gitignore now

**Comment by benkmugo** [comment]
+1

**Pull request merged**
