### PR TITLE
Add state change/assign to the audit log

### PR DESCRIPTION
**Pull request by thiagocamposviana**
We just ran into an issue on one of our customers where it would have been really good to know who made a state change. Thus it would be good to make this an audit log event.

### CODE REVIEW

**Comment by peterkeung** [comment]
Can you create an equivalent PR in the eZ repo? Then I can create a support ticket with them and reference the PR.

**Comment by thiagocamposviana** [comment]
https://github.com/ezsystems/ezpublish-legacy/pull/1285

**Comment by peterkeung** [comment]
I've created a support ticket with eZ for this

**Comment by pkamps** [comment]
I tested the pull request and it works.
Should we consider to report the old state ID? To me, it's not a critical issue - so +1

**Comment by peterkeung** [comment]
+1

**Pull request merged**
