### PR TITLE
Remove object link if user removes a related object in the objectrelationlist datatype attribute

### PR DESCRIPTION
**Pull request by pkamps**
That's how it was fixed in the ez enterprise version. Some code styling isn't correct but I didn't fix it in order to stay as close as possible to what ez system did to fix the issue.

I did some tests, seems to work fine also in a multi-lang setup.

### CODE REVIEW

**Comment by peterkeung** [comment]
Renaming $attribute to $contentObjectAttribute makes the changes look more involved than they are.

I'm +1 on the basis that we also tested this on a client.

**Comment by pkamps** [comment]
ez system pull request:
https://github.com/ezsystems/ezpublish-legacy/pull/1277

**Comment by benkmugo** [comment]
+1 on the basis of existing enterprise patch + client test + fairly simple changes

**Comment by pkamps** [comment]
This got now merged on upstream:
https://github.com/ezsystems/ezpublish-legacy/pull/1314

**Pull request merged**
