### PR TITLE
SQL injection patch in content view

### PR DESCRIPTION
**Pull request by peterkeung**
As identified in May 2016

### CODE REVIEW

**Comment by peterkeung** [comment]
@benkmugo @pkamps @ernestob

**Comment by thiagocamposviana** [comment]
This patch seems really weird.

Original line is:

( $language !== false ? $language : $this->CurrentLanguage )

Then they patched as:

$db->escapeString( $language ?: $this->CurrentLanguage )

Instead of:

$db->escapeString( $language !== false ? $language  : $this->CurrentLanguage )

Isn't this wrong?

**Comment by dougplant** [comment]
At a guess, a type-safe comparison to "false" is not desired here, and 
that is what is being fixed.


IMHO, this would be passible:

$db->escapeString( $language ? $language : $this->CurrentLanguage )

using "?:" is, IMHO, sufficiently embarrassing to be wrong

**Comment by pkamps** [comment]
Code changes look good to me. I like that the code line is not so long anymore. I'm not used to the ':?' Syntax but I think it's ok to use it. Dropping the safe comparison is good IMHO.

**Pull request merged**
